In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

# add git submodule to path to allow imports to work
submodule_name = 'AlphaTrade'
#(parent_folder_path, current_dir) = os.path.split(os.path.abspath(''))
sys.path.append(os.path.join(os.path.abspath(''), submodule_name))


In [6]:
import pandas as pd

In [3]:
sys.path

['/nfs/home/peern/LOBS5',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '',
 '/nfs/home/peern/rlenv/lib/python3.8/site-packages',
 '/nfs/home/peern/LOBS5',
 '/nfs/home/peern/rlenv/lib/python3.8/site-packages/IPython/extensions',
 '/nfs/home/peern/.ipython',
 '/nfs/home/peern/LOBS5/AlphaTrade']

In [50]:
from gymnax_exchange.jaxob.jorderbook import OrderBook
import gymnax_exchange.jaxob.JaxOrderbook as job

In [4]:
b = OrderBook(price_levels=10, orderQueueLen=10)
b

In [ ]:
# TODO: load message data from file and test b.process_orders_array(msgs)
#       and b.process_order(quote:Dict,from_data=False,verbose=False):

In [51]:
m_df = pd.read_csv(
    'data/raw/GOOG_2023-01-03_34200000_57600000_message_10.csv',
    index_col=False,
    #header=None,
    names=['timestamp', 'type', 'order_id', 'quantity', 'price', 'side'])

b_df = pd.read_csv(
    'data/raw/GOOG_2023-01-03_34200000_57600000_orderbook_10.csv',
    index_col=False,
    header=None
)

/nfs/home/peern/rlenv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/nfs/home/peern/rlenv/lib/python3.8/site-packages/pandas/util/_decorators.py:311: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  return func(*args, **kwargs)


In [35]:
# should be "trader_id" for multiple agents
m['trade_id'] = 0
m.timestamp = m.timestamp.astype(str)
m

timestamp  type   order_id  quantity   price  side  trade_id
0        34200.001061298     4   26617106       185  898500    -1         0
1        34200.001095123     4   26617106       100  898500    -1         0
2        34200.002310775     1   26628478      1700  897000     1         0
3        34200.002364829     1   26628606      2300  897600     1         0
4        34200.002446746     1   26628742      2254  897800     1         0
...                  ...   ...        ...       ...     ...   ...       ...
1962415  57599.985151757     1  905843398      6159  896800     1         0
1962416  57599.985166759     1  905843410      6159  897600    -1         0
1962417  57599.985729067     1  905843602     11600  897200    -1         0
1962418  57599.986159522     1  905843674      4500  897300    -1         0
1962419  57599.986217028     1  905843686      6500  897400    -1         0

[1962420 rows x 7 columns]

In [36]:
m.iloc[0].to_dict()

{'timestamp': '34200.001061298',
 'type': 4,
 'order_id': 26617106,
 'quantity': 185,
 'price': 898500,
 'side': -1,
 'trade_id': 0}

In [47]:
b.orderbook_array.shape

(2, 10, 10, 6)

In [38]:
trades, order_array = b.process_order(m.iloc[0].to_dict())

[       5       -1      185   898500        0 26617106    34200  1061298]
[[[[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   ...
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]]

  [[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   ...
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]]

  [[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   ...
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]]

  ...

  [[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   ...
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]]

  [[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   ...
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]]

  [[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   ...
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]
   [-1 -1 -1 -1 -1 -1]]]


 [[[-1 -1 -1 -1 -1 -1]
   [-1 -1 -1

In [45]:
m.iloc[0].to_dict()

{'timestamp': '34200.001061298',
 'type': 4,
 'order_id': 26617106,
 'quantity': 185,
 'price': 898500,
 'side': -1,
 'trade_id': 0}

In [44]:
order_array

Array([       5,       -1,      185,   898500,        0, 26617106,
          34200,  1061298], dtype=int32)

In [48]:
orderbookLevels = 10

In [49]:
import jax.numpy as jnp

In [86]:
from typing import Optional, Union
import numpy as np


def init_msgs_from_l2(book: Union[pd.Series, np.ndarray]) -> jnp.ndarray:
    orderbookLevels = len(book) // 4  # price/quantity for bid/ask
    data = jnp.array(book).reshape(int(orderbookLevels*2),2)
    newarr = jnp.zeros((int(orderbookLevels*2),8))
    initOB = newarr \
        .at[:,3].set(data[:,0]) \
        .at[:,2].set(data[:,1]) \
        .at[:,0].set(1) \
        .at[0:orderbookLevels*4:2,1].set(-1) \
        .at[1:orderbookLevels*4:2,1].set(1) \
        .at[:,4].set(0) \
        .at[:,5].set(job.INITID) \
        .at[:,6].set(34200) \
        .at[:,7].set(0).astype('int32')
    return initOB

def msgs_to_jnp(m_df: pd.DataFrame) -> jnp.ndarray:
    cols = ['Time', 'Type', 'OrderID', 'Quantity', 'Price', 'Side']
    if m_df.shape[1] == 7:
        cols += ["TradeID"]
    m_df.columns = cols
    m_df['TradeID'] = 0  #  TODO: should be TraderID for multi-agent support
    col_order=['Type','Side','Quantity','Price','TradeID','OrderID','Time']
    m_df = m_df[col_order]
    m_df = m_df[(m_df['Type'] != 6) & (m_df['Type'] != 7) & (m_df['Type'] != 5)]
    time = m_df["Time"].astype('string').str.split('.',expand=True)
    m_df[["TimeWhole","TimeDec"]] = time.astype('int32')
    m_df = m_df.drop("Time", axis=1)
    mJNP = jnp.array(m_df)
    return mJNP

def reset_orderbook(
        b: OrderBook,
        l2_book: Optional[Union[pd.Series, np.ndarray]] = None,
    ) -> None:
    b.orderbook_array = b.orderbook_array.at[:].set(-1)
    if l2_book is not None:
        msgs = init_msgs_from_l2(l2_book)
        b.process_orders_array(msgs)

In [80]:
b = OrderBook(price_levels=10, orderQueueLen=10)
b

In [90]:
reset_orderbook(b, b_df.iloc[0])

In [91]:
b.orderbook_array

Array([[[[     307,   898500,        0, 90000000,    34200,        0],
         [      -1,       -1,       -1,       -1,       -1,       -1],
         [      -1,       -1,       -1,       -1,       -1,       -1],
         ...,
         [      -1,       -1,       -1,       -1,       -1,       -1],
         [      -1,       -1,       -1,       -1,       -1,       -1],
         [      -1,       -1,       -1,       -1,       -1,       -1]],

        [[       6,   899800,        0, 90000000,    34200,        0],
         [      -1,       -1,       -1,       -1,       -1,       -1],
         [      -1,       -1,       -1,       -1,       -1,       -1],
         ...,
         [      -1,       -1,       -1,       -1,       -1,       -1],
         [      -1,       -1,       -1,       -1,       -1,       -1],
         [      -1,       -1,       -1,       -1,       -1,       -1]],

        [[      22,   900200,        0, 90000000,    34200,        0],
         [      -1,       -1,       -1,      

In [87]:
replay = msgs_to_jnp(m_df)

In [92]:
trades = b.process_orders_array(replay[:1000])

In [94]:
b.get_L2_state()

Array([899700,     22, 899100,    122, 899900,    100, 899000,    100,
       900000,    100, 898800,    118, 900600,    100, 898700,    272,
       900700,     66, 898600,    100, 900900,     13,     -1,      0,
           -1,      0,     -1,      0,     -1,      0,     -1,      0,
           -1,      0,     -1,      0,     -1,      0,     -1,      0],      dtype=int32)

In [93]:
b.orderbook_array

Array([[[[       22,    899700,         0,  27274166,     34200,
          996828344],
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         ...,
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         [       -1,        -1,        -1,        -1,        -1,
                 -1]],

        [[       99,    899900,         0,  27213982,     34200,
          892262942],
         [        1,    899900,         0,  27222734,     34200,
          909743549],
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         ...,
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         [       -1,        -1,        -1,        -1,        -1,
                 -1],
         [   